SELECT *
FROM supermarket_sales

--SHOW NUMBER OF ROWS IN DATASET

SELECT COUNT(*) AS TOTAL_ROWS
FROM supermarket_sales

--FIND THE UNIQUE CITY

SELECT DISTINCT(CITY)
FROM supermarket_sales

--DISPLAY WERE THE CITY IS YANGON AND MANDALAY

SELECT *
FROM supermarket_sales
WHERE CITY  IN('YANGON','MANDALAY')

--CALCULATE THE TOTAL  FOR ALL THE CITIES

SELECT ROUND(SUM(TOTAL),0) AS TOTAL
FROM supermarket_sales

--CALCULATE THE AVERAGE UNIT PRICE FOR THE PRODUCT HEALTH AND BEAUTY

SELECT AVG([Unit _price]) AS AVGRAGE,[Product _line]
FROM supermarket_sales
WHERE [Product _line] LIKE 'HE%'
GROUP BY [Product _line]

--DISPLAY PRODUCTS THAT STARTS WITH E

SELECT *
FROM supermarket_sales
WHERE [Product _line] LIKE 'E%'

--DISPLAY PRODUCTS THAT STARTS WITH E AND S

SELECT *
FROM supermarket_sales
WHERE [Product _line] LIKE 'E%' OR [Product _line] LIKE 'S%'

--CALCULATE THE AVG COGS

SELECT ROUND(AVG(COGS),0) AS AVG_COGS,CITY
FROM supermarket_sales
GROUP BY CITY
ORDER BY AVG_COGS ASC

--CALCULATE THE AVERAGE GROSS_INCOME 

SELECT AVG([gross _income]) AS AVG_GROSS
FROM supermarket_sales
GROUP BY CITY
HAVING AVG([gross _income])>15
ORDER BY AVG_GROSS ASC

--DISPLAY TOTAL NUMBER OF FEMALES AND MALES LIVING IN YANGON
SELECT GENDER,CITY,COUNT(GENDER) AS TOTAL
FROM supermarket_sales
WHERE CITY='YANGON'
GROUP BY GENDER,CITY

--CALCULATE THE SINGLE UNIT PRICE OF HEALTH AND BEAUTY IF QUANTITY IS 7

SELECT [Product _line],Avg([Unit _price])/AVG(Quantity) AS SINGLE_PRICE_PRODUCT
from supermarket_sales
WHERE [Product _line] LIKE 'HE%'
GROUP BY [Product _line]

--DISPLAY THE TOP 3 RATINGS

SELECT TOP 3 [Product _line],ROUND(AVG(RATING),2) AS AVG_RATING
FROM supermarket_sales
GROUP BY [Product _line]
ORDER BY AVG_RATING DESC

--FIND THE PRODUCT WITH THE MAXIMUM TAX 

SELECT [Product _line],MAX([Tax 5%]) AS MAX
FROM supermarket_sales
GROUP BY [Product _line]

--FIND THE TOTAL WHICH IS GREATER THAN 600 USING SUBQUERY 

SELECT *
FROM supermarket_sales
WHERE COGS IN
(SELECT cogs
FROM supermarket_sales
WHERE TOTAL>600
)

--CALCULATE NEW TAX FOR THE PRODUCTS

SELECT BRANCH,[Customer_ type],[Tax 5%],[Product _line],
CASE
  WHEN [Product _line]='HEALTH AND BEAUTY' THEN [Tax 5%]+0.3
 ELSE  [Tax 5%]+0.2
END AS NEW_TAX
FROM supermarket_sales

--DIFFERENT THE METHOD OF PAYMENTS
SELECT BRANCH,[Customer_ type],[Product _line],PAYMENT,
CASE
  WHEN Payment='CASH' THEN 'OFFLINE PURCHASE'
  WHEN Payment='EWALLET' THEN 'ONLINE PURCHASE'
  ELSE 'CARD TRANSCATION'
END AS METHOD
FROM supermarket_sales

